catcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path
from . import views
# single dot means current directory or root


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup', views.signup, name='signup'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>', views.cats_detail, name='cats_detail'),
    path('cats/<int:cat_id>/edit/', views.cats_edit, name='cats_edit'),
    path('cats/<int:cat_id>/delete/', views.cats_delete, name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/',
         views.add_feeding, name='add_feeding'),
    # amazon photos s3
    path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),
    # associate a toy with a cat (M:M)
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/',
         views.assoc_toy, name='assoc_toy'),
    path('cats/<int:cat_id>/deassoc_toy/<int:toy_id>/',
         views.deassoc_toy, name='deassoc_toy'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_color = models.CharField(max_length=50)


# Many to Many


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField(default=0)
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
# psql (=>) \d+ main_app_cat_toys

    def __str__(self):
        return self.name

    def fed_for_today(self):
        return self.feedings.filter(date=date.today()).count() >= len(MEALS)


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    cat = models.ForeignKey(
        Cat, on_delete=models.CASCADE, related_name="feedings")

    def __str__(self):
        return f"{self.cat.name} was feed {self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date', 'cat']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cat_id: {self.cat_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Cat, Feeding


class Cat_Form(ModelForm):
    class Meta:
        model = Cat
        labels = {'name': 'Cat Name'}
        fields = ['name', 'breed', 'description', 'age']


class Feeding_Form(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
import uuid
import boto3
from .models import Cat, Toy, Photo
from .forms import Cat_Form, Feeding_Form
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# the line below add @login_required
from django.contrib.auth.decorators import login_required


# Add these "constants" below the imports
S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollection'

# Create your views here.


def home(req):
    return render(req, 'home.html')


def about(req):
    return render(req, 'about.html')


# Add new view
@login_required
def cats_index(req):
    # create
    if req.method == 'POST':
        cat_form = Cat_Form(req.POST)
        if cat_form.is_valid():
            new_cat = cat_form.save(commit=False)
            new_cat.user = req.user
            new_cat.save()
            return redirect('index')

    # Retrieve list of cats, filtered by the
    # logged-in user stored on the request object
    cats = Cat.objects.filter(user=req.user)
    # You could also retrieve the logged in user's cats like this
    # cats = request.user.cat_set.all()
    cat_form = Cat_Form()
    context = {'cats': cats, 'cat_form': cat_form}
    return render(req, 'cats/index.html', context)


@login_required
def cats_detail(req, cat_id):
    cat = Cat.objects.get(id=cat_id)
    feeding_form = Feeding_Form()
    toys_cat_doesnt_have = Toy.objects.exclude(
        id__in=cat.toys.all().values_list('id'))
    context = {'cat': cat, 'feeding_form': feeding_form,
               'available_toys': toys_cat_doesnt_have}
    return render(req, 'cats/detail.html', context)


@login_required
def cats_edit(req, cat_id):
    cat = Cat.objects.get(id=cat_id)
    if req.method == 'POST':
        cat_form = Cat_Form(req.POST, instance=cat)
        if cat_form.is_valid():
            cat_form.save()
            return redirect('cats_detail', cat_id=cat.id)

    cat_form = Cat_Form(instance=cat)
    context = {'cat_form': cat_form, 'cat': cat}
    return render(req, 'cats/edit.html', context)


@login_required
def cats_delete(req, cat_id):
    Cat.objects.get(id=cat_id).delete()
    return redirect('index')
# =================== Feeding routes =========================


@login_required
def add_feeding(req, cat_id):
    # create the ModelForm using the data in request.POST
    form = Feeding_Form(req.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('cats_detail', cat_id=cat_id)

# =================== toy routes =========================


@login_required
def assoc_toy(req, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    return redirect('cats_detail', cat_id=cat_id)


@login_required
def deassoc_toy(req, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toys.remove(toy_id)
    return redirect('cats_detail', cat_id=cat_id)

# =================== Photo routes =========================


@login_required
def add_photo(request, cat_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, cat_id=cat_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('cats_detail', cat_id=cat_id)

# =================== Auth routes =========================


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A GET or a bad POST request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


# Add the Cat class & list and view function below the imports
# class Cat:  # Note that parens are optional if not inheriting from another class
#     def __init__(self, name, breed, description, age):
#         self.name = name
#         self.breed = breed
#         self.description = description
#         self.age = age


# cats = [
#     Cat('Lolo', 'tabby', 'foul little demon', 3),
#     Cat('Sachi', 'tortoise shell', 'diluted tortoise shell', 0),
#     Cat('Raven', 'black tripod', '3 legged cat', 4)
# ]

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<div style="text-align: center">
  <h1>About the Cat Collector</h1>
  <hr />
  <p>Hire the Cat Collector!</p>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Cat Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;CatCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">View All My Cats</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <!-- New link below -->
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2019 Cat Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}
<h1>Cat Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_delete' cat.id %}" class="btn red">Delete</a>
        <a href="{% url 'cats_edit' cat.id %}" class="btn blue">Edit</a>
      </div>
    </div>
<!-- Insert photo markup below this comment -->
        {% for photo in cat.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' cat.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
          {% csrf_token %}
          <input type="file" name="photo-file">
          <br><br>
          <input type="submit" class="btn" value="Upload Photo">
        </form>
      </div>
  <div class="col s6">
  <form action="{% url 'add_feeding' cat.id %}" method="POST">
    {% csrf_token %}
    {{ feeding_form.as_p }}
    <input type="submit" value="Add Feeding" class="btn">
  </form>
    <br>
    {% if cat.fed_for_today %}
      <div class="card-panel teal-text center-align">{{cat.name}} has been fed all meals for today</div>
    {% else %}
      <div class="card-panel red-text center-align">{{cat.name}} might be hungry</div>
    {% endif %}

  <table class="striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Meal</th>
    </tr>
    <thead>
    <tbody>
    {% for feeding in cat.feedings.all %}
      <tr>
        <td>
          {{feeding.date}}
        </td>
        <td>{{feeding.get_meal_display}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% comment %} this is toys {% endcomment %}
<hr>
<div class="row">
  <div class="col s6">
    {% if cat.toys.all %}
    {% for toy in cat.toys.all %}

    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color:{{toy.color}}"> {{toy.name}}</span>
        </span>
        <div class="card-actions">
          <a href="{% url 'deassoc_toy' cat.id toy.id %}" class="btn red">Remove</a>
        </div>
      </div>
    </div>

    {% endfor %}
    {% else %}
    <h5>No toys :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    {% for toy in available_toys %}

    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color:{{toy.color}}"> {{toy.name}}</span>
        </span>
      </div>
        <div class="card-action">
            <a href="{% url 'assoc_toy' cat.id toy.id %}" class="btn blue">Add</a>
        </div>
    </div>

    {% endfor %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

    const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock content %}
{% comment %} {{cat.feeding_set.all}} {% endcomment %}

main_app/templates/cats/edit.html
{% extends 'base.html' %} {% block content %}
<h1>Edit Cat {{ cat.name }}</h1>
<form action="{% url 'cats_edit' cat.id %}" method="POST">
  {%csrf_token %} {{ cat_form.as_p }}
  <input class="btn" type="submit" value="Edit Cat" />
</form>
{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<div class="row">
  <h1>Cat List</h1>
  <div class="col s9">
    {% for cat in cats %}
    <div class="card">
      <a href="{% url 'cats_detail' cat.id %}">
        <div class="card-content">
          <span class="card-title">{{ cat.name }}</span>
          <p>Breed: {{ cat.breed }}</p>
          <p>Description: {{ cat.description }}</p>
          {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
          {% else %}
          <p>Age: Kitten</p>
          {% endif %}
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <div class="col s3">
    <form action="{% url 'index' %}" method="POST">
      {%csrf_token %} {{ cat_form.as_p }}
      <input class="btn" type="submit" value="Add Cat" />
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<div style="text-align: center">
  <h1>Welcome</h1>
  <h2>You are on the</h2>
  <h3>home page</h3>
  <h6>Stay classy San Deigo</h6>
</div>
{% endblock %}